print("(Mikä nimesi on?)")
name = input()
print("Moikka, " + name + "!")

print("kirjoita ympyrän säde:")
radius = float(input())
print("Ympyrän pinta-ala on " + str(3.14 * radius ** 2))

print("kirjoita suorakulman kanta ja korkeus:")
base = float(input())
height = float(input())
print("Suorakulman pinta-ala on " + str(base * height))
print("neliön piiri on " + str(4 * base))

print("kirjoita kolme kokonaislukua:")
a = int(input())
b = int(input())
c = int(input())
print("Lukujen summa, tulo ja keskiarvo ovat " + str(a + b + c) + ", " + str(a * b * c) + " ja " + str((a + b + c) / 3))

print("Anna leiviskien määrä:")
leiviskat = float(input())
print("Leiviskän paino on " + str(leiviskat * 8.512) + " kg")
print("Anna naulojen määrä:")
naulat = float(input())
print("Naulan paino on " + str(naulat * 0.426) + " kg")
print("Anna luotien määrä:")
luodit = float(input())
print("Luodin paino on " + str(luodit * 0.0133) + " kg")
print("Massa nykymittojen mukaan on " + str(leiviskat * 8.512 + naulat * 0.426 + luodit * 0.0133) + " kg") 
